package com.zincstate.manifest.integrity

import android.content.Context
import com.google.android.play.core.integrity.IntegrityManagerFactory
import com.google.android.play.core.integrity.IntegrityTokenRequest
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.tasks.await
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Helper class to request Play Integrity tokens.
 *
 * Usage:
 * 1. Call [requestIntegrityToken] with a server-generated nonce.
 * 2. Send the returned token to your backend server for decryption & verification.
 * 3. Your server decrypts the token using Google's Play Integrity API and reads the verdict.
 *
 * Note: The token itself is encrypted and can only be decoded server-side via
 * Google's `playintegrity.decodeIntegrityToken` API.
 *
 * @see <a href="https://developer.android.com/google/play/integrity/overview">Play Integrity docs</a>
 */
@Singleton
class PlayIntegrityHelper @Inject constructor(
    @ApplicationContext private val context: Context
) {
    private val integrityManager = IntegrityManagerFactory.create(context)

    /**
     * Requests an integrity token from the Play Integrity API.
     *
     * @param nonce A unique, single-use token generated by your server to prevent replay attacks.
     *              Must be a Base64-encoded string (URL-safe, no padding).
     * @return The encrypted integrity token string, or null if the request failed.
     */
    suspend fun requestIntegrityToken(nonce: String): String? {
        return try {
            val request = IntegrityTokenRequest.builder()
                .setNonce(nonce)
                .build()

            val response = integrityManager.requestIntegrityToken(request).await()
            val token = response.token()

            Timber.d("Play Integrity token obtained successfully")
            token
        } catch (e: Exception) {
            Timber.e(e, "Failed to obtain Play Integrity token")
            null
        }
    }
}
